export const keeperYears = [
  {
    player: 'Bam Adebayo',
    cost: '12',
    yearsKept: '1',
    owner: 'Benson',
  },
  {
    player: 'Brandon Ingram',
    cost: '2',
    yearsKept: '1',
    owner: 'Benson',
  },
  {
    player: "De'Aaron Fox",
    cost: '6',
    yearsKept: '2',
    owner: 'Benson',
  },
  {
    player: 'Devin Booker',
    cost: '41',
    yearsKept: '1',
    owner: 'Benson',
  },
  {
    player: 'Deandre Ayton',
    cost: '16',
    yearsKept: '2',
    owner: 'Donald',
  },
  {
    player: 'Ja Morant',
    cost: '7',
    yearsKept: '1',
    owner: 'Donald',
  },
  {
    player: 'Zion Williamson',
    cost: '14',
    yearsKept: '1',
    owner: 'Donald',
  },
  {
    player: 'John Collins',
    cost: '15',
    yearsKept: '2',
    owner: 'Gabe',
  },
  {
    player: 'Shai Gilgeous-Alexander',
    cost: '5',
    yearsKept: '1',
    owner: 'Gabe',
  },
  {
    player: 'Jamaal Murray',
    cost: '7',
    yearsKept: '1',
    owner: 'JJ',
  },
  {
    player: 'Jonathan Isaac',
    cost: '5',
    yearsKept: '1',
    owner: 'JJ',
  },
  {
    player: 'Gordon Hayward',
    cost: '5',
    yearsKept: '1',
    owner: 'Nate',
  },
  {
    player: 'Jaren Jackson Jr.',
    cost: '7',
    yearsKept: '2',
    owner: 'Nate',
  },
  {
    player: 'Pascal Siakam',
    cost: '21',
    yearsKept: '1',
    owner: 'Nate',
  },
  {
    player: 'Trae Young',
    cost: '7',
    yearsKept: '2',
    owner: 'Nate',
  },
  {
    player: 'Donovan Mitchell',
    cost: '11',
    yearsKept: '3',
    owner: 'Preston',
  },
  {
    player: 'Domantas Sabonis',
    cost: '8',
    yearsKept: '1',
    owner: 'Ray',
  },
  {
    player: 'Jayson Tatum',
    cost: '17',
    yearsKept: '1',
    owner: 'Ray',
  },
  {
    player: 'Luka Doncic',
    cost: '12',
    yearsKept: '2',
    owner: 'Ray',
  },
  {
    player: 'James Harden',
    cost: '60',
    yearsKept: '1',
    owner: 'Ryan',
  },
  {
    player: 'Ricky Rubio',
    cost: '2',
    yearsKept: '1',
    owner: 'Ryan',
  },
];
